/* audit/baseline.c — see audit/baseline.h. */
#include "audit/baseline.h"

#include <stdio.h>
#include <string.h>

void ob_baseline_free(ob_baseline *bl) {
    ob_vec_free(&bl->fingerprints);
    ob_vec_free(&bl->matched);
}

ob_baseline_err ob_baseline_load(const char *path, ob_baseline *out) {
    ob_vec_init(&out->fingerprints, OB_FINGERPRINT_LEN);
    ob_vec_init(&out->matched, sizeof(int));

    FILE *f = fopen(path, "r");
    if (!f) {
        return OB_BASELINE_ERR_OPEN;
    }

    char line[OB_FINGERPRINT_LEN + 16];
    while (fgets(line, sizeof(line), f)) {
        size_t n = strlen(line);
        while (n > 0 && (line[n - 1] == '\n' || line[n - 1] == '\r' ||
                         line[n - 1] == ' '  || line[n - 1] == '\t')) {
            line[--n] = '\0';
        }
        if (n == 0 || line[0] == '#') {
            continue;
        }
        if (n >= OB_FINGERPRINT_LEN) {
            fclose(f);
            ob_baseline_free(out);
            return OB_BASELINE_ERR_LINE_TOO_LONG;
        }
        char *slot = (char *)ob_vec_push(&out->fingerprints);
        int  *m    = (int *)ob_vec_push(&out->matched);
        if (!slot || !m) {
            fclose(f);
            ob_baseline_free(out);
            return OB_BASELINE_ERR_OPEN;
        }
        memcpy(slot, line, n + 1);
        *m = 0;
    }
    fclose(f);
    return OB_BASELINE_OK;
}

int ob_baseline_contains(const ob_baseline *bl, const char *fingerprint) {
    size_t n = ob_vec_count(&bl->fingerprints);
    for (size_t i = 0; i < n; i++) {
        const char *fp = (const char *)ob_vec_at_const(&bl->fingerprints, i);
        if (strcmp(fp, fingerprint) == 0) {
            return 1;
        }
    }
    return 0;
}

size_t ob_baseline_apply(ob_baseline *bl, ob_finding_list *fl) {
    size_t suppressed = 0;
    size_t i = 0;
    while (i < ob_finding_list_count(fl)) {
        const ob_finding *f = ob_finding_list_at(fl, i);
        int found = 0;
        size_t bn = ob_vec_count(&bl->fingerprints);
        for (size_t j = 0; j < bn; j++) {
            const char *fp = (const char *)ob_vec_at_const(&bl->fingerprints, j);
            if (strcmp(fp, f->fingerprint) == 0) {
                int *m = (int *)ob_vec_at(&bl->matched, j);
                if (m) {
                    *m = 1;
                }
                found = 1;
                break;
            }
        }
        if (found) {
            ob_vec_remove_at(&fl->v, i);
            suppressed++;
        } else {
            i++;
        }
    }
    return suppressed;
}

size_t ob_baseline_stale_count(const ob_baseline *bl) {
    size_t n = ob_vec_count(&bl->matched);
    size_t stale = 0;
    for (size_t i = 0; i < n; i++) {
        const int *m = (const int *)ob_vec_at_const(&bl->matched, i);
        if (m && *m == 0) {
            stale++;
        }
    }
    return stale;
}

const char *ob_baseline_stale_at(const ob_baseline *bl, size_t idx) {
    size_t n = ob_vec_count(&bl->matched);
    size_t seen = 0;
    for (size_t i = 0; i < n; i++) {
        const int *m = (const int *)ob_vec_at_const(&bl->matched, i);
        if (m && *m == 0) {
            if (seen == idx) {
                return (const char *)ob_vec_at_const(&bl->fingerprints, i);
            }
            seen++;
        }
    }
    return NULL;
}

int ob_baseline_write(const char *path, const ob_finding_list *fl) {
    FILE *f = fopen(path, "w");
    if (!f) {
        return -1;
    }
    fprintf(f, "# onebin baseline v1\n");
    fprintf(f, "# generated by: onebin audit --write-baseline\n");
    size_t n = ob_finding_list_count(fl);
    for (size_t i = 0; i < n; i++) {
        const ob_finding *fd = ob_finding_list_at(fl, i);
        fprintf(f, "%s\n", fd->fingerprint);
    }
    fclose(f);
    return 0;
}
