/* static-everywhere: choose software rendering when there is no GL.
 *
 * The forwarder generated by tools/gen-optional-lib-forwarder.sh removes
 * libGL from DT_NEEDED, so the binary starts on a host that has no GL at
 * all. That is necessary but not sufficient: Qt would still try to use
 * OpenGL and fail.
 *
 * Qt does not decide this at runtime. From qtdeclarative's
 * qsgcontextplugin.cpp, the scene graph falls back to the software
 * adaptation only when the BUILD lacks OpenGL/Vulkan/Metal, or when the
 * platform integration reports no RhiBasedRendering capability. This
 * build has OpenGL and xcb reports RHI-capable, so nothing here happens
 * by itself -- the choice has to be made before Qt looks.
 *
 * Hence a constructor, which runs before main() and therefore before
 * QGuiApplication:
 *
 *   QT_QUICK_BACKEND=software        qsgcontextplugin.cpp reads this to
 *                                    select the scene graph adaptation.
 *   QT_XCB_GL_INTEGRATION=none       qxcbconnection.cpp then skips GLX
 *                                    and EGL entirely, and handles their
 *                                    absence gracefully.
 *
 * Both are set with overwrite=0. Someone who has chosen a backend gets
 * to keep it, including the tests, which set QT_QUICK_BACKEND themselves.
 *
 * The probe is a dlopen of its own rather than a call into the
 * forwarder's state, so this file does not depend on which constructor
 * ran first. dlopen is reference-counted and the second call is cheap.
 */
#include <dlfcn.h>
#include <stdlib.h>
#include <stdio.h>

/* Report the render-backend decision when SE_RENDER_DEBUG is set.
 *
 * The switch to software rendering happens before main(), silently, which
 * is right for normal use but leaves a user with a black window no way to
 * tell whether the fallback fired, chose wrong, or never ran. One opt-in
 * line closes that gap. Off by default so a normal launch stays quiet;
 * f4-diag sets it, and a user can too. */
static void se_render_log(const char *msg, const char *soname)
{
    if (getenv("SE_RENDER_DEBUG")) {
        if (soname) {
            fprintf(stderr, "[se-render] %s (libGL: %s)\n", msg, soname);
        } else {
            fprintf(stderr, "[se-render] %s\n", msg);
        }
    }
}

__attribute__((constructor)) static void se_select_render_backend(void)
{
    /* Same override the forwarder honours, so the no-GL path can be
       exercised on a machine that has GL. Without it this code is
       unfalsifiable in CI. */
    const char *override = getenv("SE_FORWARD_SE_GL_SONAME");
    const char *soname = (override && *override) ? override : "libGL.so.1";

    void *h = dlopen(soname, RTLD_LAZY | RTLD_LOCAL);
    if (h) {
        dlclose(h);
        se_render_log("libGL present; leaving the render backend to Qt", soname);
        return;
    }

    se_render_log("libGL absent; selecting software rendering", soname);
    setenv("QT_QUICK_BACKEND", "software", 0);
    setenv("QT_XCB_GL_INTEGRATION", "none", 0);
}
