/* static-everywhere: choose software rendering when there is no GL.
 *
 * The forwarder generated by tools/gen-optional-lib-forwarder.sh removes
 * libGL from DT_NEEDED, so the binary starts on a host that has no GL at
 * all. That is necessary but not sufficient: Qt would still try to use
 * OpenGL and fail.
 *
 * Qt does not decide this at runtime. From qtdeclarative's
 * qsgcontextplugin.cpp, the scene graph falls back to the software
 * adaptation only when the BUILD lacks OpenGL/Vulkan/Metal, or when the
 * platform integration reports no RhiBasedRendering capability. This
 * build has OpenGL and xcb reports RHI-capable, so nothing here happens
 * by itself -- the choice has to be made before Qt looks.
 *
 * Hence a constructor, which runs before main() and therefore before
 * QGuiApplication:
 *
 *   QT_QUICK_BACKEND=software        qsgcontextplugin.cpp reads this to
 *                                    select the scene graph adaptation.
 *   QT_XCB_GL_INTEGRATION=none       qxcbconnection.cpp then skips GLX
 *                                    and EGL entirely, and handles their
 *                                    absence gracefully.
 *
 * Both are set with overwrite=0. Someone who has chosen a backend gets
 * to keep it, including the tests, which set QT_QUICK_BACKEND themselves.
 *
 * The probe is a dlopen of its own rather than a call into the
 * forwarder's state, so this file does not depend on which constructor
 * ran first. dlopen is reference-counted and the second call is cheap.
 */
#include <dlfcn.h>
#include <stdlib.h>
#include <stdio.h>

/* Report the render-backend decision when debugging is requested.
 *
 * The switch to software rendering happens before main(), silently, which
 * is right for normal use but leaves a user with a black window no way to
 * tell whether the fallback fired, chose wrong, or never ran. One opt-in
 * line closes that gap. Off by default so a normal launch stays quiet.
 *
 * SE_RENDER_DEBUG keeps the original stderr behaviour for a direct launch.
 * SE_RENDER_DEBUG_FILE is the protocol-safe mode used by f4-diag: it makes
 * the same one line go to a sidecar file instead, and takes precedence over
 * stderr when both variables are set. A failed sidecar open is deliberately
 * silent; writing an error to stderr would put the diagnostic back into the
 * f4 stream that this mode exists to avoid. */
static void se_render_log(const char *msg, const char *soname)
{
    const char *path = getenv("SE_RENDER_DEBUG_FILE");
    FILE *stream = stderr;
    int close_stream = 0;

    if (path && *path) {
        stream = fopen(path, "a");
        if (!stream) {
            return;
        }
        close_stream = 1;
    } else if (!getenv("SE_RENDER_DEBUG")) {
        return;
    }

    if (soname) {
        fprintf(stream, "[se-render] %s (libGL: %s)\n", msg, soname);
    } else {
        fprintf(stream, "[se-render] %s\n", msg);
    }
    if (close_stream) {
        fclose(stream);
    }
}

/* Can this process actually obtain an OpenGL context?
 *
 * The first version of this probe asked only whether libGL.so.1 could be
 * dlopen'd, and that answer was wrong on the first real desktop: libGL
 * was present, the probe said "leave it to Qt", and Qt then died with
 *
 *   QXcbIntegration: Cannot create platform OpenGL context, neither GLX
 *                    nor EGL are enabled
 *   Failed to initialize graphics backend for OpenGL.
 *
 * because presence of the library says nothing about whether a context
 * can be created here -- the GL integration may be missing, the display
 * may not offer GLX, the driver may be unusable. So the probe now
 * exercises the thing it is deciding about: it opens the display and
 * asks GLX for its version, then falls back to asking EGL to initialise.
 * Either succeeding means Qt has a real chance; both failing means
 * software rendering, chosen here rather than discovered by Qt at the
 * cost of the process.
 *
 * Everything is done through dlopen/dlsym so this file links with no GL
 * or X headers and no new load-time dependency: a binary that must run
 * where these libraries are absent cannot afford to need them to start.
 */
static int se_glx_works(const char *gl_soname)
{
    void *gl = NULL, *x11 = NULL;
    void *(*p_XOpenDisplay)(const char *) = NULL;
    int (*p_XCloseDisplay)(void *) = NULL;
    int (*p_glXQueryVersion)(void *, int *, int *) = NULL;
    void *dpy = NULL;
    int major = 0, minor = 0, ok = 0;

    gl = dlopen(gl_soname, RTLD_LAZY | RTLD_LOCAL);
    if (!gl) {
        return 0;
    }
    /* glXQueryVersion is the cheapest call that proves the GLX extension
       is actually answering on this display, not merely that the client
       library exists. */
    *(void **)(&p_glXQueryVersion) = dlsym(gl, "glXQueryVersion");
    if (!p_glXQueryVersion) {
        dlclose(gl);
        return 0;
    }

    x11 = dlopen("libX11.so.6", RTLD_LAZY | RTLD_LOCAL);
    if (!x11) {
        dlclose(gl);
        return 0;
    }
    *(void **)(&p_XOpenDisplay) = dlsym(x11, "XOpenDisplay");
    *(void **)(&p_XCloseDisplay) = dlsym(x11, "XCloseDisplay");
    if (p_XOpenDisplay && p_XCloseDisplay) {
        dpy = p_XOpenDisplay(NULL);
        if (dpy) {
            ok = p_glXQueryVersion(dpy, &major, &minor) ? 1 : 0;
            p_XCloseDisplay(dpy);
        }
    }

    dlclose(x11);
    dlclose(gl);
    return ok;
}

static int se_egl_works(void)
{
    void *egl = NULL;
    void *(*p_eglGetDisplay)(void *) = NULL;
    unsigned int (*p_eglInitialize)(void *, int *, int *) = NULL;
    void *dpy = NULL;
    int major = 0, minor = 0, ok = 0;

    egl = dlopen("libEGL.so.1", RTLD_LAZY | RTLD_LOCAL);
    if (!egl) {
        return 0;
    }
    *(void **)(&p_eglGetDisplay) = dlsym(egl, "eglGetDisplay");
    *(void **)(&p_eglInitialize) = dlsym(egl, "eglInitialize");
    if (p_eglGetDisplay && p_eglInitialize) {
        /* EGL_DEFAULT_DISPLAY is (void *)0. */
        dpy = p_eglGetDisplay((void *)0);
        if (dpy) {
            ok = p_eglInitialize(dpy, &major, &minor) ? 1 : 0;
        }
    }
    dlclose(egl);
    return ok;
}

__attribute__((constructor)) static void se_select_render_backend(void)
{
    /* Same override the forwarder honours, so the no-GL path can be
       exercised on a machine that has GL. Without it this code is
       unfalsifiable in CI. */
    const char *override = getenv("SE_FORWARD_SE_GL_SONAME");
    const char *soname = (override && *override) ? override : "libGL.so.1";

    /* An explicit choice by the user or the caller is not second-guessed:
       setenv below uses overwrite=0, but the probe itself is skipped too,
       so forcing software costs nothing at startup. */
    if (getenv("QT_QUICK_BACKEND")) {
        se_render_log("QT_QUICK_BACKEND already set; leaving it alone", NULL);
        return;
    }

    if (se_glx_works(soname)) {
        se_render_log("GLX context available; leaving the render backend to Qt",
                      soname);
        return;
    }
    if (se_egl_works()) {
        se_render_log("EGL available; leaving the render backend to Qt", NULL);
        return;
    }

    se_render_log("no usable GLX or EGL; selecting software rendering", soname);
    setenv("QT_QUICK_BACKEND", "software", 0);
    setenv("QT_XCB_GL_INTEGRATION", "none", 0);
}
