#!/usr/bin/env bash
# Generate a C file that makes a shared library OPTIONAL at load time.
#
# The problem it solves
# ---------------------
# A library named on the link line becomes a DT_NEEDED entry, and the
# dynamic loader resolves those before main(). So a binary linked against
# libGL does not start at all on a host without libGL -- no fallback
# logic ever runs, because no code of ours runs.
#
# The generated file defines every symbol the library exports, so the
# linker never needs the library itself and records no dependency on it.
# Each definition is a three-instruction tail-call to a pointer resolved
# once by dlopen/dlsym at startup. If the library is absent the pointer
# stays null and the call returns zero instead of crashing.
#
# Why assembly rather than C wrappers
# -----------------------------------
# A C wrapper needs the exact prototype of what it forwards, and there
# are thousands of GL and GLX entry points. The trampoline touches no
# argument register at all, so every signature -- integer, float, struct
# by value, variadic -- is forwarded correctly by construction rather
# than by a table someone has to maintain.
#
# It is emitted as a global asm() block inside a normal .c file, so no
# project needs enable_language(ASM) to consume it.
#
# Usage: gen-optional-lib-forwarder.sh <soname> <prefix> <library-path> <output.c>
#   soname        what to dlopen at runtime, e.g. libGL.so.1
#   prefix        C identifier prefix for the generated globals, e.g. se_gl
#   library-path  the library to read the exported symbol list FROM
#   output.c      file to write

set -euo pipefail

if [ "$#" -ne 4 ]; then
    printf 'usage: %s <soname> <prefix> <library-path> <output.c>\n' "$0" >&2
    exit 2
fi

SONAME="$1"
PREFIX="$2"
LIBPATH="$3"
OUT="$4"

if [ ! -e "$LIBPATH" ]; then
    printf '%s: no such library: %s\n' "$0" "$LIBPATH" >&2
    exit 1
fi

# Only exported code symbols. Data symbols cannot be forwarded by a
# tail-call and libGL exports none; if one ever appears, leaving it out
# means the link fails loudly rather than producing a binary that
# silently reads the wrong address.
SYMBOLS=$(nm -D --defined-only "$LIBPATH" 2>/dev/null \
          | awk '$2 == "T" || $2 == "i" { print $3 }' \
          | grep -E '^[A-Za-z_][A-Za-z0-9_]*$' \
          | sort -u)

if [ -z "$SYMBOLS" ]; then
    printf '%s: no exported code symbols found in %s\n' "$0" "$LIBPATH" >&2
    exit 1
fi

COUNT=$(printf '%s\n' "$SYMBOLS" | wc -l)

{
    printf '/* Generated by tools/gen-optional-lib-forwarder.sh -- do not edit.\n'
    printf ' *\n'
    printf ' * Makes %s optional at load time: %s symbols are defined here\n' "$SONAME" "$COUNT"
    printf ' * and forwarded to the real library if it can be opened.\n'
    printf ' */\n'
    printf '#include <dlfcn.h>\n'
    printf '#include <stdlib.h>\n\n'

    printf '/* One pointer per symbol, resolved once at startup. */\n'
    printf '%s\n' "$SYMBOLS" | while IFS= read -r s; do
        printf 'void *%s_%s;\n' "$PREFIX" "$s"
    done

    printf '\nstatic void *%s_handle;\n\n' "$PREFIX"

    printf 'int %s_available(void) { return %s_handle != 0; }\n\n' "$PREFIX" "$PREFIX"

    printf '__attribute__((constructor))\n'
    printf 'static void %s_resolve(void)\n{\n' "$PREFIX"
    printf '    /* A test hook, and only that: the absent-library path cannot be\n'
    printf '       exercised on a machine that has the library, so allow the\n'
    printf '       soname to be redirected. */\n'
    printf '    const char *override = getenv("SE_FORWARD_%s_SONAME");\n' "$(printf '%s' "$PREFIX" | tr '[:lower:]' '[:upper:]')"
    printf '    const char *soname = (override && *override) ? override : "%s";\n' "$SONAME"
    printf '    %s_handle = dlopen(soname, RTLD_LAZY | RTLD_LOCAL);\n' "$PREFIX"
    printf '    if (!%s_handle) {\n        return;\n    }\n' "$PREFIX"
    printf '%s\n' "$SYMBOLS" | while IFS= read -r s; do
        printf '    %s_%s = dlsym(%s_handle, "%s");\n' "$PREFIX" "$s" "$PREFIX" "$s"
    done
    printf '}\n\n'

    printf '__asm__(\n'
    printf '".text\\n"\n'
    n=0
    printf '%s\n' "$SYMBOLS" | while IFS= read -r s; do
        n=$((n + 1))
        printf '".globl %s\\n.type %s,@function\\n"\n' "$s" "$s"
        printf '"%s:\\n"\n' "$s"
        printf '"  movq %s_%s@GOTPCREL(%%rip), %%rax\\n"\n' "$PREFIX" "$s"
        printf '"  movq (%%rax), %%rax\\n"\n'
        printf '"  testq %%rax, %%rax\\n"\n'
        printf '"  je %s_null_%s\\n"\n' "$PREFIX" "$s"
        printf '"  jmp *%%rax\\n"\n'
        printf '"%s_null_%s:\\n"\n' "$PREFIX" "$s"
        printf '"  xorl %%eax, %%eax\\n"\n'
        printf '"  ret\\n"\n'
    done
    printf ');\n'
} >"$OUT"

printf 'generated %s: %s symbols forwarding to %s\n' "$OUT" "$COUNT" "$SONAME"
