#!/usr/bin/env python3
"""Keep the KDE projects of the Konsole build at the commits in kde-sources.lock.

kde-builder cannot clone a bare commit: before a first clone it checks the
pin with `git ls-remote`, which lists refs only. In an existing clone it
fetches and checks out a `commit:` option without that check. So:

  clone SRC_DIR      clone every locked project missing from SRC_DIR
                     (before kde-builder runs; cached checkouts are kept)
  verify SRC_DIR     fail unless every locked project's HEAD is its pin
                     (after kde-builder has built)
  sync-template      write one `commit:` per locked project into
                     kde-builder.yaml.in
  check [GRAPH]      preflight: the template is in sync with the lock, no
                     project has two override blocks, and the lock covers
                     exactly the resolved graph minus Konsole and the
                     template's ignore-projects
  reachable          preflight: every pin is a commit on its repository's
                     default branch (a treeless clone per project)

A project that already has a hand-written `override` block gets its
`commit:` line inside that block: a second `override <name>:` key would
silently replace the first when the YAML is loaded.
"""
import concurrent.futures
import os
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
# The override exists for tools/test-konsole-source-pins.sh only.
LOCK = pathlib.Path(os.environ.get("KONSOLE_SOURCE_PINS_LOCK",
                                   ROOT / "contrib/konsole/kde-sources.lock"))
TEMPLATE = ROOT / "contrib/konsole/kde-builder.yaml.in"
GRAPH = ROOT / "contrib/konsole/kde-graph.txt"
BEGIN = "# BEGIN kde-sources.lock pins -- generated by tools/konsole-source-pins.py sync-template"
END = "# END kde-sources.lock pins"
HEADER = re.compile(r"^override ([A-Za-z0-9_.+-]+):\s*$")


def die(message):
    print(f"konsole-source-pins: {message}", file=sys.stderr)
    sys.exit(1)


def load_lock(path=LOCK):
    pins = {}
    for number, line in enumerate(path.read_text().splitlines(), 1):
        if not line.strip() or line.startswith("#"):
            continue
        fields = line.split()
        if len(fields) != 3:
            die(f"{path.name}:{number}: expected <project> <commit> <repository>")
        name, commit, url = fields
        if not re.fullmatch(r"[0-9a-f]{40}", commit):
            die(f"{path.name}:{number}: {name}: not a full commit id: {commit}")
        if not url.startswith(("https://", "file://")):
            die(f"{path.name}:{number}: {name}: repository must be https: {url}")
        if name in pins:
            die(f"{path.name}:{number}: {name} is pinned twice")
        pins[name] = (commit, url)
    if not pins:
        die(f"{path.name} pins nothing")
    return pins


def synced(text, pins):
    lines = text.split("\n")
    # Drop the generated section; it is rebuilt below.
    if BEGIN in lines:
        start = lines.index(BEGIN)
        try:
            end = lines.index(END, start)
        except ValueError:
            die(f"{TEMPLATE.name}: generated section has no end marker")
        del lines[start:end + 1]
        while start > 0 and start <= len(lines) and lines[start - 1] == "":
            del lines[start - 1]
            start -= 1
    out = []
    in_block = None
    hand_written = set()
    for line in lines:
        match = HEADER.match(line)
        if match:
            in_block = match.group(1)
            out.append(line)
            if in_block in pins:
                out.append(f'  commit: "{pins[in_block][0]}"')
                hand_written.add(in_block)
            continue
        if line and not line.startswith(" "):
            in_block = None
        if in_block is not None and re.match(r"^\s+commit:", line):
            continue
        out.append(line)
    while out and out[-1] == "":
        out.pop()
    generated = [name for name in pins if name not in hand_written]
    if generated:
        out += ["", BEGIN]
        for name in generated:
            out += [f"override {name}:", f'  commit: "{pins[name][0]}"']
        out.append(END)
    return "\n".join(out) + "\n"


def ignore_projects(text):
    names, active = [], False
    for line in text.splitlines():
        if re.match(r"^\s+ignore-projects:\s*$", line):
            active = True
            continue
        if active:
            match = re.match(r"^\s+-\s+(\S+)\s*$", line)
            if match:
                names.append(match.group(1))
                continue
            break
    return set(names)


def check(graph_path):
    pins = load_lock()
    text = TEMPLATE.read_text()
    problems = []
    headers = [m.group(1) for m in map(HEADER.match, text.splitlines()) if m]
    for name in sorted({h for h in headers if headers.count(h) > 1}):
        problems.append(f"{TEMPLATE.name} has more than one 'override {name}:' block")
    if synced(text, pins) != text:
        problems.append(f"{TEMPLATE.name} is out of sync with {LOCK.name}; "
                        "run tools/konsole-source-pins.py sync-template")
    graph = {line.strip() for line in graph_path.read_text().splitlines()
             if line.strip() and not line.startswith("#")}
    expected = graph - {"konsole"} - ignore_projects(text)
    for name in sorted(expected - set(pins)):
        problems.append(f"{name} is built but not pinned in {LOCK.name}")
    for name in sorted(set(pins) - expected):
        problems.append(f"{name} is pinned but not built (not in {graph_path.name}, or ignored)")
    if problems:
        die("\n  " + "\n  ".join(problems))
    print(f"konsole-source-pins: {len(pins)} KDE projects pinned; template and graph agree")


def git(*args, **kwargs):
    return subprocess.run(["git", *args], check=True, text=True, **kwargs)


def clone(source_dir):
    pins = load_lock()
    source_dir.mkdir(parents=True, exist_ok=True)
    for name, (commit, url) in pins.items():
        tree = source_dir / name
        if (tree / ".git").exists():
            continue
        if tree.exists() and any(tree.iterdir()):
            die(f"{tree} exists but is not a Git checkout")
        print(f"konsole-source-pins: cloning {name} for pin {commit[:12]}", flush=True)
        git("clone", "--quiet", "--recursive", url, str(tree))
        git("-C", str(tree), "cat-file", "-e", f"{commit}^{{commit}}")


def verify(source_dir):
    pins = load_lock()
    wrong = []
    for name, (commit, _url) in pins.items():
        tree = source_dir / name
        if not (tree / ".git").exists():
            wrong.append(f"{name}: no checkout at {tree}")
            continue
        head = git("-C", str(tree), "rev-parse", "HEAD",
                   capture_output=True).stdout.strip()
        if head != commit:
            wrong.append(f"{name}: built {head}, pinned {commit}")
    if wrong:
        die("KDE sources are not at their pins:\n  " + "\n  ".join(wrong))
    print(f"konsole-source-pins: all {len(pins)} KDE projects built at their pins")


def reachable():
    pins = load_lock()

    def probe(item):
        name, (commit, url) = item
        with tempfile.TemporaryDirectory() as tmp:
            repo = pathlib.Path(tmp) / "repo.git"
            cloned = subprocess.run(
                ["git", "clone", "--quiet", "--bare", "--filter=tree:0", url, str(repo)],
                capture_output=True, text=True, timeout=600)
            if cloned.returncode != 0:
                return f"{name}: cannot clone {url}: {cloned.stderr.strip()}"
            on_head = subprocess.run(
                ["git", "-C", str(repo), "merge-base", "--is-ancestor", commit, "HEAD"],
                capture_output=True, text=True)
            if on_head.returncode != 0:
                return f"{name}: {commit} is not on the default branch of {url}"
        return None

    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
        problems = [p for p in pool.map(probe, pins.items()) if p]
    if problems:
        die("pins that cannot be checked out:\n  " + "\n  ".join(problems))
    print(f"konsole-source-pins: all {len(pins)} pins are commits on their default branches")


def main(argv):
    if len(argv) < 2:
        die("usage: konsole-source-pins.py clone|verify SRC_DIR | sync-template | check [GRAPH] | reachable")
    command = argv[1]
    if command in ("clone", "verify") and len(argv) == 3:
        (clone if command == "clone" else verify)(pathlib.Path(argv[2]))
    elif command == "sync-template" and len(argv) == 2:
        TEMPLATE.write_text(synced(TEMPLATE.read_text(), load_lock()))
    elif command == "reachable" and len(argv) == 2:
        reachable()
    elif command == "check" and len(argv) in (2, 3):
        check(pathlib.Path(argv[2]) if len(argv) == 3 else GRAPH)
    else:
        die(f"bad arguments: {' '.join(argv[1:])}")


if __name__ == "__main__":
    main(sys.argv)
